import java.awt.Color;


/**
 *
 * @author Jorg
 */

public class login extends javax.swing.JFrame {

    int xMouse, yMouse;
        
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        JorgInd = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        headerLogo = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        userTxt = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        userSp = new javax.swing.JSeparator();
        PswTxt = new javax.swing.JLabel();
        PswSp = new javax.swing.JSeparator();
        passwordTF = new javax.swing.JPasswordField();
        loginBx = new javax.swing.JPanel();
        loginTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JorgInd.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        JorgInd.setForeground(new java.awt.Color(255, 255, 255));
        JorgInd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JorgInd.setText("Jorg Industries");
        BG.add(JorgInd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 200, 60));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        Logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BG.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 200, 150));

        City.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/city.png"))); // NOI18N
        BG.add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 200, 500));

        headerLogo.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        headerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/favicon.png"))); // NOI18N
        headerLogo.setText("JORG Inc.");
        BG.add(headerLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        login.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        login.setText("LOGIN");
        BG.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        userTxt.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        userTxt.setText("User");
        BG.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        userTF.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        userTF.setForeground(new java.awt.Color(204, 204, 204));
        userTF.setText("Insert your username");
        userTF.setBorder(null);
        userTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTFMousePressed(evt);
            }
        });
        userTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTFActionPerformed(evt);
            }
        });
        BG.add(userTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 520, 30));
        BG.add(userSp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 520, -1));

        PswTxt.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        PswTxt.setText("Password");
        BG.add(PswTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        BG.add(PswSp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 520, -1));

        passwordTF.setForeground(new java.awt.Color(204, 204, 204));
        passwordTF.setText("********");
        passwordTF.setBorder(null);
        passwordTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTFMousePressed(evt);
            }
        });
        BG.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 312, 520, 30));

        loginBx.setBackground(new java.awt.Color(0, 134, 190));

        loginTxt.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        loginTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTxt.setText("Login");
        loginTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginBxLayout = new javax.swing.GroupLayout(loginBx);
        loginBx.setLayout(loginBxLayout);
        loginBxLayout.setHorizontalGroup(
            loginBxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        loginBxLayout.setVerticalGroup(
            loginBxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        BG.add(loginBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        exitTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 774, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BG.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void loginTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTxtMouseEntered
        loginBx.setBackground(new Color(78, 184, 222));
        loginTxt.setForeground(Color.black);

    }//GEN-LAST:event_loginTxtMouseEntered

    private void loginTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTxtMouseExited
        loginBx.setBackground(new Color(0, 134, 190));
        loginTxt.setForeground(Color.white);

    }//GEN-LAST:event_loginTxtMouseExited

    private void userTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTFMousePressed
        if (userTF.getText().equals("Insert your username")){
            userTF.setText("");
            userTF.setForeground(Color.black);
        }
        if (String.valueOf(passwordTF.getPassword()).isEmpty()){
            passwordTF.setText("********");
            passwordTF.setForeground(Color.gray);    
        }
        
    }//GEN-LAST:event_userTFMousePressed

    private void passwordTFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTFMousePressed
        if (userTF.getText().isEmpty()){
            userTF.setText("Insert your username");
        userTF.setForeground(Color.gray);
        }
        if (String.valueOf(passwordTF.getPassword()).equals("********")){
            passwordTF.setText("");
            passwordTF.setForeground(Color.black);
        }
        
        

    }//GEN-LAST:event_passwordTFMousePressed

    private void loginTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTxtMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Login made with the following values: \n User: " + userTF.getText() + "\n Password: " + String.valueOf(passwordTF.getPassword()), "Login" , javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_loginTxtMouseClicked

    private void userTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel City;
    private javax.swing.JLabel JorgInd;
    private javax.swing.JLabel Logo;
    private javax.swing.JSeparator PswSp;
    private javax.swing.JLabel PswTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerLogo;
    private javax.swing.JLabel login;
    private javax.swing.JPanel loginBx;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JSeparator userSp;
    private javax.swing.JTextField userTF;
    private javax.swing.JLabel userTxt;
    // End of variables declaration//GEN-END:variables
}
